version: "3"

services:
  backend:
    container_name: backend
    image: jhj967878/plantit:django_ai
    volumes:
      - ./server:/project/server
    working_dir: /project/server
    command: bash -c "service redis-server start && gunicorn --bind 0:8000 server.wsgi:application"

    expose:
      - 8000

  nginx:
    container_name: nginx
    image: nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./server:/project/server
      - ./nginx/config:/etc/nginx/conf.d
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/data:/var/www/certbot
    restart: always
    depends_on:
      - backend

  certbot:
    image: certbot/certbot:latest
    command: certonly --webroot --webroot-path=/var/www/certbot --email jhj967878@naver.com --agree-tos --no-eff-email -d elice-kdt-2nd-team3.koreacentral.cloudapp.azure.com
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/logs:/var/log/letsencrypt
      - ./certbot/data:/var/www/certbot
    
